// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsvqjmdvuccethfmtsmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzdnFqbWR2dWNjZXRoZm10c21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTU5MTAsImV4cCI6MjA2NDc5MTkxMH0.9utcQGdzAUsbqkfJjygaD4dwR8rbmTGUZBpGvf03S-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);